# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_testauth_api import paps_pb2 as grpc__testauth__api_dot_paps__pb2


class FleetsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserStatsByCorporation = channel.unary_stream(
        '/Fleets/GetUserStatsByCorporation',
        request_serializer=grpc__testauth__api_dot_paps__pb2.GetUserStatsByCorporationRequest.SerializeToString,
        response_deserializer=grpc__testauth__api_dot_paps__pb2.UserFleetParticipationStats.FromString,
        )


class FleetsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUserStatsByCorporation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FleetsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserStatsByCorporation': grpc.unary_stream_rpc_method_handler(
          servicer.GetUserStatsByCorporation,
          request_deserializer=grpc__testauth__api_dot_paps__pb2.GetUserStatsByCorporationRequest.FromString,
          response_serializer=grpc__testauth__api_dot_paps__pb2.UserFleetParticipationStats.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Fleets', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
