# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='paps.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\npaps.proto\"\x92\x01\n\x1bUserFleetParticipationStats\x12\x1e\n\x16primary_character_name\x18\x01 \x01(\t\x12\x1c\n\x14primary_character_id\x18\x02 \x01(\x03\x12\x1a\n\x12thirty_day_average\x18\x03 \x01(\x05\x12\x19\n\x11sixty_day_average\x18\x04 \x01(\x05\":\n GetUserStatsByCorporationRequest\x12\x16\n\x0e\x63orporation_id\x18\x01 \x01(\x03\x62\x06proto3')
)




_USERFLEETPARTICIPATIONSTATS = _descriptor.Descriptor(
  name='UserFleetParticipationStats',
  full_name='UserFleetParticipationStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='primary_character_name', full_name='UserFleetParticipationStats.primary_character_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='primary_character_id', full_name='UserFleetParticipationStats.primary_character_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thirty_day_average', full_name='UserFleetParticipationStats.thirty_day_average', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sixty_day_average', full_name='UserFleetParticipationStats.sixty_day_average', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=161,
)


_GETUSERSTATSBYCORPORATIONREQUEST = _descriptor.Descriptor(
  name='GetUserStatsByCorporationRequest',
  full_name='GetUserStatsByCorporationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='corporation_id', full_name='GetUserStatsByCorporationRequest.corporation_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['UserFleetParticipationStats'] = _USERFLEETPARTICIPATIONSTATS
DESCRIPTOR.message_types_by_name['GetUserStatsByCorporationRequest'] = _GETUSERSTATSBYCORPORATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserFleetParticipationStats = _reflection.GeneratedProtocolMessageType('UserFleetParticipationStats', (_message.Message,), dict(
  DESCRIPTOR = _USERFLEETPARTICIPATIONSTATS,
  __module__ = 'paps_pb2'
  # @@protoc_insertion_point(class_scope:UserFleetParticipationStats)
  ))
_sym_db.RegisterMessage(UserFleetParticipationStats)

GetUserStatsByCorporationRequest = _reflection.GeneratedProtocolMessageType('GetUserStatsByCorporationRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERSTATSBYCORPORATIONREQUEST,
  __module__ = 'paps_pb2'
  # @@protoc_insertion_point(class_scope:GetUserStatsByCorporationRequest)
  ))
_sym_db.RegisterMessage(GetUserStatsByCorporationRequest)


# @@protoc_insertion_point(module_scope)
